### ISSUE TITLE
Handling Errors

### ISSUE THREAD

**Issue by brandonmikeska** [leocavalcante/meteor-redux#1]
Hey how do you handle errors. Like say this was an example of a todo app. How do you handle errors if a write to the database fails? Does every state carry an error object?

**Comment by leocavalcante** [comment]
Hi @brandonmikeska, this was a 3 days case study, I don't recommend using it for productions apps, instead of you are really sure of what the code is doing and changing or implementing by or own risk, like error handling. My conclusion for now was that its not worth it using Redux/Flux approach on Meteor since it is heavily tied to sessions, collections, methods, pub/subs etc and Meteor already proposes a way of architect things.
